name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: checkout master
      uses: actions/checkout@master
      
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.4.0
      with:
        dotnet-version: '3.1.100'

    # dotnet build        
    - name: Build with dotnet
      run: dotnet build --configuration Release      

    # publish the app
    - name: dotnet publish
      run: |
        dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp 
    - name: 'Run Azure webapp deploy action using publish profile credentials'
      uses: azure/webapps-deploy@v1
      with: 
        app-name: dotnetcoredemoblizz # Replace with your app name
        publish-profile: ${{ secrets.dotnetcoredemoblizzPubProfile }} # Define secret variable in repository settings as per action documentation
        package: ${{env.DOTNET_ROOT}}/myapp